### ISSUE TITLE
Ubuntu support

### ISSUE THREAD

**Issue by craigrs84** [frida/frida-clr#8]
Can the the CLR bindings be compiled and used with .NET Core on Ubuntu?  If yes, can you post instructions?  Thanks

**Comment by oleavr** [comment]
No they cannot as they're built using C++/CLI. A major rewrite would be needed. (If you're interested in helping out with that, that would be awesome!)

**Comment by craigrs84** [comment]
thanks.  I was poking around and it looks like they added C++/CLI in .NET Core 3.1 but I think it's only for Windows for now.
