### ISSUE TITLE
.Net 4.0 frida-clr-12.9.4 Exception

### ISSUE THREAD

**Issue by FuzzySecurity** [frida/frida-clr#9]
I wanted to create a small C# utility but I'm getting a file not found exception at runtime. I grabbed the latest x64 clr release from Github and added it as a reference in my project.

**Environment:** Win10 x64, .NET 4.0, frida 12.9.4, build-arch x64

**Repro test-case:**

```c#
using System;
using Frida;

namespace Londor
{
	class Program
	{
		public static void FridaGetDevices()
		{
			DeviceManager dm = new DeviceManager(System.Windows.Threading.Dispatcher.CurrentDispatcher);
			Device[] devices = dm.EnumerateDevices();
			foreach(Device d in devices)
			{
				Console.WriteLine("Device: " + d.Name);
			}
		}

		static void Main(string[] args)
		{
			FridaGetDevices();
		}
	}
}
```

**Compile**:

```
1>------ Rebuild All started: Project: Londor, Configuration: Release x64 ------
1>  Londor -> C:\Users\b33f\Tools\Dev\Frida-CLR-Test\Londor\Londor\bin\x64\Release\Londor.exe
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========
```

**Runtime**:

```
C:\Users\b33f>C:\Users\b33f\Tools\Dev\Frida-CLR-Test\Londor\Londor\bin\x64\Release\Londor.exe

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Frida, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
   at Londor.Program.FridaGetDevices()
   at Londor.Program.Main(String[] args) in C:\Users\b33f\Tools\Dev\Frida-CLR-Test\Londor\Londor\Program.cs:line 26
```

Am I missing a dependency here?

**Comment by FuzzySecurity** [comment]
I had some time and did a bit of investigating, I looked at "NAME NOT FOUND" events in procmon and I saw that the process looks for "frida.dll" in the release folder at runtime.

![image](https://user-images.githubusercontent.com/10997340/83660259-83afe980-a5bc-11ea-8d93-eeca2bb6df94.png)

However VS copies the resource with it's original name (csproj) to the build folder, eg "frida-clr-12.9.4-windows-x86_64.dll", once I changed this, the test-case runs fine.

![image](https://user-images.githubusercontent.com/10997340/83660424-bc4fc300-a5bc-11ea-9e55-3aabd1d79693.png)

I would have thought that the build would take care of this name resolution. Anyway, maybe Frida can publish a nuget package, I think people would really like that and it would simplify the development process.

Feel free to tag this as a feature request or close the issue.

**Comment by oleavr** [comment]
Thanks for looking into this!

> maybe Frida can publish a nuget package

That's a great idea 👌  I've sadly got way too much on my plate to get to this anytime soon, but PRs are most welcome 😊 The Windows CI build steps are [here](https://github.com/frida/frida-ci/blob/13859e728e604850719411f461ce9a57fcb4bc64/master.cfg#L166-L290).
